# Generated by Django 2.1 on 2018-08-05 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lt_car_plates', '0002_delete_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='carplate',
            name='car_model',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carplate',
            name='car_brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carplate',
            name='plate_number',
            field=models.CharField(max_length=10),
        ),
    ]
