# Generated by Django 2.1 on 2018-08-06 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lt_car_plates', '0004_auto_20180805_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='carplate',
            name='owner_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
